### ISSUE TITLE
Elegir y comprar aspectos

### ISSUE THREAD

**Issue by R3Ngfx** [UNIZAR-30226-2021-01/PS_Risk_android#12]
Permitir a los usuarios comprar y elegir distintos iconos y aspectos de tropas desde la configuración del perfil

**Comment by pkmniako** [comment]
Cuando un usuario se registra, la tienda indica que tiene 0 monedas para iconos o aspectos. Esto no es un problema de la aplicación android, si no del backend. ([Issue 7](https://github.com/UNIZAR-30226-2021-01/PS_Risk_server/issues/7))

11b6613 cierra este issue.
